jaxws:
  build: jaxws
  #hostname: jaxws
  ports:
    - "8082:8082"
  links:
    - logstash:logstash
  mem_limit: 512m

jaxrs:
  build: jaxrs
  #hostname: jaxrs
  ports:
    - "8081:8081"
  links:
    - logstash:logstash
    - jaxws
  mem_limit: 512m

elasticsearch:
  image: deviantony/elk-elasticsearch:latest
  ports:
    - "9200:9200"

logstash:
  image: deviantony/elk-logstash
  volumes:
    - ./logstash-conf:/etc/logstash/conf.d:ro
  ports:
    - "514/udp"
    - "514/tcp"
    - "12201/udp"
    - "12201/tcp"
  links:
    - elasticsearch
  mem_limit: 256m

kibana:
  build: docker-elk-kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  mem_limit: 256m


logspout:
  image: gliderlabs/logspout:latest
  volumes:
    - ./var/run/docker.sock:/tmp/docker.sock

